// aski-core — the rkyv contract types.
//
// Every type that appears in the rkyv message between askicc
// and askic is defined here. Generated by corec from core/*.aski.
//
// Run `corec core generated/aski_core.rs` to regenerate.

include!("../generated/aski_core.rs");
