/// cc — the core compiler.
///
/// Reads aski-core's .aski files and emits Rust source.
/// The bootstrap seed — the one hardcoded parser.

mod lex;
#[cfg(test)]
mod lex_tests;
mod parse;
#[cfg(test)]
mod parse_tests;
mod codegen;

use std::fs;
use std::path::Path;

fn main() {
    let core_dir = Path::new("core");
    let out_dir = Path::new("generated");

    fs::create_dir_all(out_dir).expect("failed to create output directory");

    let mut all_output = String::new();
    all_output.push_str("// Generated by cc from aski-core .aski files.\n");
    all_output.push_str("// Do not edit — regenerate with `cc`.\n\n");

    let mut files: Vec<_> = fs::read_dir(core_dir)
        .expect("failed to read core/ directory")
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map(|x| x == "aski").unwrap_or(false))
        .collect();

    files.sort_by_key(|e| e.path());

    for entry in &files {
        let path = entry.path();
        let source = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("failed to read {}: {}", path.display(), e));

        let tokens = lex::lex(&source)
            .unwrap_or_else(|e| panic!("lex error in {}: {}", path.display(), e));

        let module = parse::parse_file(tokens)
            .unwrap_or_else(|e| panic!("parse error in {}: {}", path.display(), e));

        let rust = codegen::emit_module(&module);

        all_output.push_str(&format!("// — from {} —\n\n", path.display()));
        all_output.push_str(&rust);
        all_output.push('\n');

        eprintln!("cc: {} → {} domains", path.display(), module.domains.len());
    }

    let out_path = out_dir.join("aski_core.rs");
    fs::write(&out_path, &all_output)
        .unwrap_or_else(|e| panic!("failed to write {}: {}", out_path.display(), e));

    eprintln!("cc: wrote {}", out_path.display());
}
